# example stages
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:

  simplehash: # create a simple hash from ftp listing
    cmd: bash stages/0_invalidate.sh
    outs: 
      - download/toxvaldb.html

  download:
    cmd: bash stages/1_download.sh
    deps: 
      - stages/1_download.sh
      - download/toxvaldb.html
    outs:
      - download/toxvaldb

  process:
    cmd: Rscript stages/2_process.R
    deps:
      - download/toxvaldb
    outs:
      - brick/toxvaldb.parquet